name: the-overlord-of-beggars

services:
  backend:
    build: ./backend
    volumes:
      - ./backend/app:/app/app
    ports:
      - '8000:8000'

  frontend:
    build: ./frontend
    volumes:
      - ./frontend/app:/app/app
    environment:
      - BACKEND_API_URL=http://backend:8000
    ports:
      - '3000:3000'
