name: 🐛 Bug Report
description: 程式好像發生問題了
labels:
  - "bug:unverified"
body:
  - type: textarea
    attributes:
      label: 預期行為
      description: 用精簡的方式描述你預期程式應該要做的行為
    validations:
      required: true
  - type: textarea
    attributes:
      label: 實際行為
      description: 用精簡的方式描述你實際程式做的行為
    validations:
      required: true
